config/routes.rb
Rails.application.routes.draw do

  get '/' => 'root#top', as: 'root'

  devise_for :c_users, controllers: {
    sessions:      'c_users/sessions',
    passwords:     'c_users/passwords',
    registrations: 'c_users/registrations'
  }
  devise_for :f_users, controllers: {
    sessions:      'f_users/sessions',
    passwords:     'f_users/passwords',
    registrations: 'f_users/registrations'
  }
  resources :requests do
    get "search" , on: :collection
    resource :favorite_stars, only: [:create, :destroy,:show]
  end

  resources :proposals do
    get "search" , on: :collection
    resource :favorite_hearts, only: [:create, :destroy,:show]
  end

  resources :chatrooms, only: [ :show, :index] do
    resources :messages, only: [:create]
  end

  resources :crops_calendars,except: [:show]
  resources :blogs
  resources :f_users, except: [:new, :create,:index]
  resources :c_users, except: [:new, :create,:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :f_user

	attachment :b_image

	enum b_category: { "収穫情報": 0, "レシピ紹介": 1, "コラボ情報": 2, "その他": 3 }

	validates :b_title, presence: true
	validates :b_body , presence: true

end

app/models/c_user.rb
class CUser < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    has_many :requests, dependent: :destroy
    has_many :proposals, through: :favorite_hearts
    has_many :favorite_hearts, dependent: :destroy
    has_many :chatrooms, dependent: :destroy

    validates :company   ,presence: true
    validates :name      ,presence: true
    validates :tell      ,presence: true ,numericality: { only_integer: true } ,length: {maximum: 11}
    validates :post_code ,presence: true ,numericality: { only_integer: true } ,length: {maximum: 7}
    validates :address   ,presence: true
    validates :industry  ,presence: true

    attachment :image

    acts_as_paranoid

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord

	has_many :messages, dependent: :destroy
	belongs_to :f_user
	belongs_to :c_user

end

app/models/crops_calendar.rb
class CropsCalendar < ApplicationRecord

	belongs_to :f_user

	validates :crops ,presence: true

end

app/models/f_user.rb
class FUser < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    has_many :blogs, dependent: :destroy
    has_many :proposals, dependent: :destroy
    has_many :requests, through: :favorite_stars
    has_many :favorite_stars, dependent: :destroy
    has_many :crops_calendars, dependent: :destroy
    has_many :chatrooms, dependent: :destroy

    validates :farm      ,presence: true
    validates :name      ,presence: true
    validates :tell      ,presence: true ,numericality: { only_integer: true } ,length: {maximum: 11}
    validates :post_code ,presence: true ,numericality: { only_integer: true } ,length: {maximum: 7}
    validates :address   ,presence: true

    attachment :image

    acts_as_paranoid

end

app/models/favorite_heart.rb
class FavoriteHeart < ApplicationRecord

	belongs_to :c_user
	belongs_to :proposal

end

app/models/favorite_star.rb
class FavoriteStar < ApplicationRecord

	belongs_to :f_user
	belongs_to :request

end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :chatroom

	validates :text, presence: true

end

app/models/proposal.rb
class Proposal < ApplicationRecord

	belongs_to :f_user
	has_many :favorite_hearts, dependent: :destroy
	has_many :c_users, through: :favorite_hearts

	attachment :p_image

	enum category: { "農作物出荷": 0, "体験/イベント": 1, "その他": 2 }

	validates :title         ,presence: true
	validates :body          ,presence: true
	validates :location      ,presence: true
	validates :start_season  ,presence: true
	validates :finish_season ,presence: true

	def favorited_by?(c_user)
		favorite_hearts.where(c_user_id: c_user.id).exists?
	end

	# 検索機能
	def self.search(search) #ここでのself.はProposal.を意味する
		if search
			where(['body LIKE ? OR location LIKE ?', "%#{search}%", "%#{search}%"]) #検索との部分一致を表示。#Proposal.は省略
		else
			all #全て表示。#Proposal.は省略
		end
	end

end

app/models/request.rb
class Request < ApplicationRecord

	belongs_to :c_user
	has_many :favorite_stars, dependent: :destroy
	has_many :f_users, through: :favorite_stars

	enum category: { "農作物出荷": 0, "体験/イベント": 1, "その他": 2 }

	validates :title         ,presence: true
	validates :body          ,presence: true
	validates :location      ,presence: true
	validates :start_season  ,presence: true
	validates :finish_season ,presence: true

	def favorited_by?(f_user)
		favorite_stars.where(f_user_id: f_user.id).exists?
	end

	# 検索機能
	def self.search(search) #ここでのself.はRequest.を意味する
		if search
			where(['body LIKE ? OR location LIKE ?', "%#{search}%", "%#{search}%"]) #検索との部分一致を表示。#Request.は省略
		else
			all #全て表示。#Request.は省略
		end
	end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	before_action :login_user ,except:[:index,:show]
	before_action :correct_user ,only:[:edit,:update,:destroy]

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.f_user_id = current_f_user.id
		if @blog.save
			redirect_to blog_path(@blog), notice:'旬ネタを投稿しました！'
		else
			render :new
		end
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])
		if @blog.update(blog_params)
			redirect_to blog_path(@blog), notice:'旬ネタを変更しました！'
		else
			render :edit
		end
	end

	def show
		@blog = Blog.find(params[:id])
		@f_user = @blog.f_user
	end

	def index
		@blogs = Blog.all.reverse_order
		@blogs_harvest = Blog.where(b_category: "0").reverse_order
		@blogs_recipe = Blog.where(b_category: "1").reverse_order
		@blogs_collabo = Blog.where(b_category: "2").reverse_order
		@blogs_b_other = Blog.where(b_category: "3").reverse_order
	end

	def destroy
		blog = Blog.find(params[:id])
		if blog.destroy
			redirect_to f_user_path(blog.f_user), notice:'旬ネタを削除しました！'
		else
			render :show
		end
	end

	def login_user
		if f_user_signed_in? || c_user_signed_in?
		else
		 redirect_to root_path
		end
	end

	def correct_user
		@user = Blog.find(params[:id]).f_user
		redirect_to root_path unless @user == current_f_user
	end

	private
	def blog_params
		params.require(:blog).permit(:f_user_id,:b_title,:b_category,:b_body,:b_image)
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def create
		@chatroom = Chatroom.find(params[:chatroom_id])
		@message = Message.new(message_params)
		@message.chatroom_id = @chatroom.id
		@messages = @chatroom.messages
		@f_user = FUser.find(@chatroom.f_user.id)
		@c_user = CUser.find(@chatroom.c_user.id)
		if current_f_user != nil
			@message.f_user = true
		else
			@message.f_user = false
		end
		if @message.save
			flash[:notice] = "メッセージが送信されました"
			render partial:'messages/messages', locals: { messages: @messages }
		else
			flash[:notice] = "メッセージが送信されませんでした"
			render partial:'messages/error_messages', locals: { messages: @messages }
		end
	end

	private
	def message_params
		params.require(:message).permit(:messenger, :text)
	end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/c_users_helper.rb
module CUsersHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/f_users_helper.rb
module FUsersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/messages/_c_user_image.html.erb
<%= link_to attachment_image_tag(@c_user, :image, :fill, 60, 60, fallback: "/images/company.png", class: "img-responsive img-circle"), @c_user  %>

app/views/messages/_error_messages.html.erb
<%= render partial:'messages/messages', locals: { messages: @messages } %>
<!-- ===== エラーメッセージ ===== -->
<% if @message.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
		<ul>
			<%= @message.errors.count %>件のエラーが発生しました。
			<% @message.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/messages/_f_user_image.html.erb
<%= link_to attachment_image_tag(@f_user, :image, :fill, 60, 60, fallback: "/images/farmer.png", class: "img-responsive img-circle"), @f_user  %>

app/views/messages/_last_message.html.erb
<p class="lastMessage">
	<% if chatroom.messages.empty? %>
		    ※ まだトークがありません ※
	<% else %>
			<%= chatroom.messages.last.text %><br>
			<span><%= chatroom.messages.last.created_at.strftime('%m月%d日 %H:%M') %></span>
	<% end %>
</p>

app/views/messages/_messages.html.erb
<% if @messages.empty? %>
	<p align="center">
		※ まだトークがありません。下記のフォームからメッセージを送信してください。 ※
	</p>
<% end %>
<% @messages.each do |message|%>
	<div class="row">

		<!-- === farmer でログインしている場合　=== -->
		<% if current_f_user %>
			<!-- チャット相手からのメッセージ -->
			<% if message.f_user == false %>
				<div class="col-md-1 col-md-offset-1 col-sm-1">
					<%= render 'messages/c_user_image',c_user:@c_user %>
				</div>
				<div class="balloon-left col-md-7 col-sm-8">
					<%= simple_format(message.text) %>
					<span><%= message.created_at.strftime('%m月%d日 %H:%M') %></span>
				</div>
			<!-- 自分が送ったメッセージ -->
			<% else %>
				<div class="balloon-right col-md-offset-3 col-md-7 col-sm-8 col-sm-offset-2">
					<%= simple_format(message.text) %>
					<span><%= message.created_at.strftime('%m月%d日 %H:%M') %></span>
				</div>
				<div class="col-md-1 col-sm-1">
					<%= render 'messages/f_user_image',f_user:@f_user %>
				</div>
			<% end %>

		<!-- === company でログインしている場合　=== -->
		<% elsif current_c_user %>
		　　<!-- チャット相手からのメッセージ -->
			<% if message.f_user == true %>
				<div class="col-md-1 col-md-offset-1 col-sm-1">
					<%= render 'messages/f_user_image',f_user:@f_user %>
				</div>
				<div class="balloon-left col-md-7 col-sm-8">
					<%= simple_format(message.text) %>
					<span><%= message.created_at.strftime('%m月%d日 %H:%M') %></span>
				</div>
			<!-- 自分が送ったメッセージ -->
			<% else %>
				<div class="balloon-right col-md-offset-3 col-md-7 col-sm-8 col-sm-offset-2">
					<%= simple_format(message.text) %>
					<span><%= message.created_at.strftime('%m月%d日 %H:%M') %></span>
				</div>
				<div class="col-md-1 col-sm-1">
					<%= render 'messages/c_user_image',c_user:@c_user %>
				</div>
			<% end %>
		<% end %>

	</div>
<% end %>

<!-- jsで下部までスクロールさせる際に必要な記述 -->
<div id="last"></div>