config/routes.rb
Rails.application.routes.draw do

  get '/' => 'root#top', as: 'root'

  devise_for :c_users, controllers: {
    sessions:      'c_users/sessions',
    passwords:     'c_users/passwords',
    registrations: 'c_users/registrations'
  }
  devise_for :f_users, controllers: {
    sessions:      'f_users/sessions',
    passwords:     'f_users/passwords',
    registrations: 'f_users/registrations'
  }
  resources :requests do
    get "search" , on: :collection
    resource :favorite_stars, only: [:create, :destroy,:show]
  end

  resources :proposals do
    get "search" , on: :collection
    resource :favorite_hearts, only: [:create, :destroy,:show]
  end

  resources :chatrooms, only: [ :show, :index] do
    resources :messages, only: [:create]
  end

  resources :crops_calendars,except: [:show]
  resources :blogs
  resources :f_users, except: [:new, :create,:index]
  resources :c_users, except: [:new, :create,:index]

end

app/models/f_user.rb
class FUser < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    has_many :blogs, dependent: :destroy
    has_many :proposals, dependent: :destroy
    has_many :requests, through: :favorite_stars
    has_many :favorite_stars, dependent: :destroy
    has_many :crops_calendars, dependent: :destroy
    has_many :chatrooms, dependent: :destroy

    validates :farm      ,presence: true
    validates :name      ,presence: true
    validates :tell      ,presence: true ,numericality: { only_integer: true } ,length: {maximum: 11}
    validates :post_code ,presence: true ,numericality: { only_integer: true } ,length: {maximum: 7}
    validates :address   ,presence: true

    attachment :image

    acts_as_paranoid

end

app/controllers/f_users/confirmations_controller.rb
# frozen_string_literal: true

class FUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/f_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class FUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/f_users/passwords_controller.rb
# frozen_string_literal: true

class FUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/f_users/registrations_controller.rb
# frozen_string_literal: true

class FUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/f_users/sessions_controller.rb
# frozen_string_literal: true

class FUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/f_users/unlocks_controller.rb
# frozen_string_literal: true

class FUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/f_users_controller.rb
class FUsersController < ApplicationController

	before_action :login_user
	before_action :correct_user ,except: [:show]
	before_action :room_user

	def edit
		@user = FUser.find(params[:id])
	end

	def update
		@user = FUser.find(params[:id])
		if @user.update(f_user_params)
			redirect_to @user,notice: '基本情報を編集しました！'
		else
			render :edit
		end
	end

	def show
		@user = FUser.find(params[:id])
		@c_user = current_c_user
		@blogs = @user.blogs.reverse_order
		@proposals = @user.proposals.reverse_order
		if @user != current_f_user && @c_user
			@chatroom = Chatroom.find_by(f_user_id: @user.id ,c_user_id: @c_user)
		end
		@crops_calendars = @user.crops_calendars
	end

	def destroy
		user = FUser.find(params[:id])
		user.destroy
		redirect_to :root
	end

	def room_user
		@f_user = FUser.find(params[:id])
		if @f_user != current_f_user && current_c_user
        	Chatroom.find_or_create_by(f_user_id: @f_user.id ,c_user_id: current_c_user.id)
        end
    end

    def login_user
    	if f_user_signed_in? || c_user_signed_in?
    	else
    		redirect_to :root
    	end
    end

    def correct_user
		@user = FUser.with_deleted.find(params[:id])
		redirect_to :root unless @user == current_f_user
	end

	private
	def f_user_params
		params.require(:f_user).permit(:name, :image, :farm, :profile, :hp_url, :tell, :post_code, :address, :conv_time, )
	end

end

app/helpers/f_users_helper.rb
module FUsersHelper
end

app/views/f_users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 form-group">
			<h3 class="glyphicon glyphicon-cog">マイファーム・基本情報編集</h3>
			<%= form_for(@user) do |f| %>

				<!-- ===== エラーメッセージ ===== -->
				<% if @user.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(@user.errors.count, "error") %> prohibited this map from being saved:</h2>
						<ul>
							<% @user.errors.full_messages.each do |message| %>
							<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				<% end %>

				<!-- ===== 入力フォーム ===== -->
				<div class="field ">
					<%= f.label :image,"◇ プロフィール写真" %>
					<%= f.attachment_field :image %>
				</div>

				<div class="field ">
					<%= f.label :name,"◇ 担当者名(お名前)" %>
					<%= f.text_field :name, autofocus: true, autocomplete: "name",placeholder:"山田太郎",class: "form-control" %>
				</div>

				<div class="field ">
					<%= f.label :farm,"◇ ファーム名" %>
					<%= f.text_field :farm, autofocus: true, autocomplete: "farm",placeholder:"コラボロ農園",class: "form-control" %>
				</div>

				<div class="field ">
					<%= f.label :profile,"◇ ファーム紹介文" %>
					<%= f.text_area :profile, autofocus: true, autocomplete: "profile",class: "form-control" %>
				</div>

				<div class="field ">
					<%= f.label :hp_url,"◇ ファームのHP" %>
					<%= f.text_field :hp_url, autofocus: true,class: "form-control" %>
				</div>

				<div class="field ">
					<%= f.label :post_code,"◇ ファームの郵便番号" %>
					<%= f.text_field :post_code, autofocus: true, autocomplete: "post_code",placeholder:"0000000",class: "form-control" %>
				</div>

				<div class="field ">
					<%= f.label :address,"◇ ファームの所在地" %>
					<%= f.text_area :address, autofocus: true, autocomplete: "address",class: "form-control"  %>
				</div>

				<div class="field ">
					<%= f.label :conv_time,"◇ 連絡の取りやすい時間" %>
					<%= f.text_field :conv_time, autofocus: true, autocomplete: "conv_time",placeholder:"平日9:00~18:00",class: "form-control"  %>
				</div>

				<div class="field ">
					<%= f.label :tell,"◇ 電話番号 ※非公開" %>
					<%= f.text_field :tell, autofocus: true, autocomplete: "tell" ,placeholder:"00000000000",class: "form-control" %>
				</div>

				<div class="field ">
					<%= f.label :email,"◇ メールアドレス ※非公開" %>
					<%= f.email_field :email, autofocus: true, autocomplete: "email",class: "form-control" %>
				</div>

				<p class="actions">
					<%= f.submit "基本情報を更新する" ,class: "btn btn-block btn-default btn-xs"%>
				</p>

	    	<% end %>
		</div>
	</div>
</div>

app/views/f_users/show.html.erb
<div class="container">
	<h3><i class="fas fa-home"></i>&ensp;
		<% if @user == current_f_user %>マイファーム
		<% else %><%= @user.farm %>
		<% end %>
	</h3>

	<!-- ===== サクセスメッセージ ===== -->
	<%= notice %>

	<!-- ===== 情報別タブボタン===== -->
	<div class="row">
		<div id="tab-menu" class="col-md-6 col-md-offset-6 clearfix" >
			<a href="#tab-all" class="tab-btn active btn col-md-4">基本情報</a>
			<a href="#tab-crops" class="tab-btn btn col-md-4">作物情報</a>
			<a href="#tab-blogs" class="tab-btn btn col-md-4">旬ネタ</a>
		</div>
	</div>

	<!-- ===== 情報別の内容 ===== -->
	<div id="tab-contents">

		<!-- === 基本情報 === -->
		<div id="tab-all" class="tab">
			<!-- ----- ユーザー基本情報 ----- -->
			<div class="basic row item">
				<p class="item-title color-base">基本情報</p>
				<div class="col-md-4 ">
					<%= attachment_image_tag @user, :image, fallback: "/images/farmer.png" ,class: "img-responsive img-thumbnail"%>
				</div>
				<div class="col-md-8">
					<table class="table table-hover">
						<tr>
							<th width="30%">◇&emsp;ファーム名</th>
							<td width="70%"><%= @user.farm %></td>
						</tr>
						<tr>
							<th width="30%">◇&emsp;担当者名</th>
							<td width="70%"><%= @user.name %></td>
						</tr>
						<tr>
							<th width="30%">◇&emsp;ファーム紹介</th>
							<td width="70%"><%= simple_format(@user.profile) %></td>
						</tr>
						<tr>
							<th width="30%">◇&emsp;ファームのHP</th>
							<td width="70%"><%= @user.hp_url %></td>
						</tr>
						<tr>
							<th width="30%">◇&emsp;所在地</th>
							<td width="70%"><%= @user. address %></td>
						</tr>
						<tr>
							<th width="30%">◇&emsp;連絡の取りやすい時間</th>
							<td width="70%"><%= @user.conv_time %></td>
						</tr>
					</table>
					<!-- リンクボタン -->
					<div class="link-btn">
						<% if @user == current_f_user %>
							<%= link_to "基本情報を編集する",[:edit,current_f_user],class: "btn btn-default col-md-7 " %>
							<%= link_to "退会する",f_user_path(@user),
								method: :delete, data: { confirm: '本当に退会しますか？'},
								class: "btn btn-default col-md-4 col-md-offset-1" %>
						<% elsif  @user != current_f_user && @c_user  %>
							<%= link_to "担当者と連絡を取る",@chatroom,class: "btn btn-block btn-default" %>
						<% end %>
					</div>
				</div>
			</div>
			<!-- ----- google map表示 ----- -->
			<div class="map row item">
				<p class="item-title color-base">所在地</p>
					<iframe
					width="100%"
					height="450"
					frameborder="0" style="border:0"
					src=<%= "https://www.google.com/maps/embed/v1/search?key=***************&q=#{@user.address}" %> allowfullscreen></iframe>
			</div>
		</div>


		<!-- === 作物情報 === -->
		<div id="tab-crops" class="tab">
			<!-- ----- 収穫カレンダー ----- -->
			<div class="calenders row item">
				<p class="item-title color-base">
					作物カレンダー
					<!-- 新規投稿ページへのリンク -->
					<% if @user == current_f_user %>
						<span class="link-btn">
							&emsp;<%= link_to "",:new_crops_calendar, class: "far fa-plus-square" %>
						</span>
					<% end %>
				</p>
				<!-- カレンダーの表示 -->
				<div class="col-md-12 col-sm-12">
					<% if @crops_calendars.empty? %>
						<p align="center">※ 登録されている作物はありません ※</p>
					<% else %>
						<table class="">
			    		<thead>
			    			<tr>
			    				<th class="crop">作物名</th>
									<% ["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"].each do |month| %>
											<th class="month"><%= month %></th>
									<% end %>
			    			</tr>
			    		</thead>
			    		<tbody>
			    			<% @crops_calendars.each do |cc| %>
				    			<tr>
				    				<th class="crop"><%= cc.crops %></th>
										<% [cc.Jan,cc.Feb,cc.Mar,cc.Apr,cc.May,cc.Jun,cc.Jul,cc.Aug,cc.Sep,cc.Oct,cc.Nov,cc.Dec].each do |c| %>
											<%if c == 2%>
											<td class="bestSeason""></td>
											<%elsif c == 1%>
											<td class="season"></td>
											<% else %>
											<td></td>
											<% end %>
										<% end %>

				    				<!-- 編集・削除ボタン -->
				    				<% if @f_user == current_f_user %>
				    				<td class="cc-edit">
				    					<%= link_to "",[:edit, cc], class: "glyphicon glyphicon-pencil" %>
				    					<%= link_to "", cc, method: :delete, data: { confirm: '本当に削除しますか？'}, class: "glyphicon glyphicon-trash" %>
				    				</td>
				    				<% end %>
				    			</tr>
			    			<% end %>
			    		</tbody>
				    </table>
			    	<p align="right" class="cc-color">
			    		<span class="bestSeason"></span>&ensp;BestSeason&emsp;
			    		<span class="season"></span>&ensp;Season
			    	</p>
					<% end %>
				</div>
			</div>

			<!-- ----- ユーザーが投稿したプロポーザル一覧 ----- -->
			<div class="row item">
				<p class="item-title color-base">
					ファームからのプロポーザル
					<!-- 新規投稿ページへのボタン -->
					<% if @user == current_f_user %>
						<span class="link-btn">
							&emsp;<%= link_to "", :new_proposal, class: "far fa-plus-square" %>
						</span>
					<% end %>
				</p>
				<div class=" row f_user_proposal">
					<% if @proposals.empty? %>
						<p align="center">※ ファームからのプロポーザルはまだありません ※</p>
					<% else %>
						<% @proposals.each do |proposal| %>
							<%= render 'proposals/proposals_index',proposal:proposal %>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>


		<!-- === 旬ネタ === -->
		<div id="tab-blogs" class="tab">
			<!-- ----- ユーザーが投稿した旬ネタ一覧 ----- -->
			<div class="row item">
				<p class="item-title color-base">
					ファーム旬ネタ
					<!-- 新規投稿ページへのボタン -->
					<% if @user == current_f_user %>
						<span class="link-btn">
							&emsp;<%= link_to "", :new_blog, class: "far fa-plus-square" %>
						</span>
					<% end %>
				</p>
				<div class="row f_user_blogs">
					<% if @blogs.empty? %>
						<p align="center">※ 投稿されている旬ネタはありません ※</p>
					<% else %>
						<% @blogs.each do |blog| %>
						<%= render 'blogs/blogs_index',blog:blog %>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>

	</div>
</div>