config/routes.rb
Rails.application.routes.draw do

  get '/' => 'root#top', as: 'root'

  devise_for :c_users, controllers: {
    sessions:      'c_users/sessions',
    passwords:     'c_users/passwords',
    registrations: 'c_users/registrations'
  }
  devise_for :f_users, controllers: {
    sessions:      'f_users/sessions',
    passwords:     'f_users/passwords',
    registrations: 'f_users/registrations'
  }
  resources :requests do
    get "search" , on: :collection
    resource :favorite_stars, only: [:create, :destroy,:show]
  end

  resources :proposals do
    get "search" , on: :collection
    resource :favorite_hearts, only: [:create, :destroy,:show]
  end

  resources :chatrooms, only: [ :show, :index] do
    resources :messages, only: [:create]
  end

  resources :crops_calendars,except: [:show]
  resources :blogs
  resources :f_users, except: [:new, :create,:index]
  resources :c_users, except: [:new, :create,:index]

end

app/models/request.rb
class Request < ApplicationRecord

	belongs_to :c_user
	has_many :favorite_stars, dependent: :destroy
	has_many :f_users, through: :favorite_stars

	enum category: { "農作物出荷": 0, "体験/イベント": 1, "その他": 2 }

	validates :title         ,presence: true
	validates :body          ,presence: true
	validates :location      ,presence: true
	validates :start_season  ,presence: true
	validates :finish_season ,presence: true

	def favorited_by?(f_user)
		favorite_stars.where(f_user_id: f_user.id).exists?
	end

	# 検索機能
	def self.search(search) #ここでのself.はRequest.を意味する
		if search
			where(['body LIKE ? OR location LIKE ?', "%#{search}%", "%#{search}%"]) #検索との部分一致を表示。#Request.は省略
		else
			all #全て表示。#Request.は省略
		end
	end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	before_action :login_user
	before_action :correct_user ,only:[:edit,:update,:destroy]

	def new
		@request = Request.new
	end

	def create
		@request = Request.new(request_params)
		@request.c_user_id = current_c_user.id
		if @request.save
			redirect_to @request, notice:'リクエストを追加しました！'
		else
			render :new
		end
	end

	def edit
		@request = Request.find(params[:id])
	end

	def update
		@request = Request.find(params[:id])
		if @request.update(request_params)
			redirect_to @request, notice:'リクエスト内容を変更しました！'
		else
			render :edit
		end
	end

	def show
		@request = Request.find(params[:id])
		@c_user = @request.c_user

		# #favorite_stars(bookmark)した人一覧を出したい
		@favorited_users = []
		@favorites = FavoriteStar.where(request_id: @request).reverse_order
		@favorites.each do |f|
			@favorited_user = FUser.find_by(id: f.f_user_id)
			@favorited_users.push(@favorited_user)
		end
	end

	def index

		@requests = Request.all.reverse_order

		#favorite_stars(bookmark)に登録したリクエストを取り出したい
		@favorites = FavoriteStar.where("f_user_id = ?", current_f_user).reverse_order
		@requests_fav = []
		@favorites.each do |f|
			@request = Request.find_by(id: f.request_id)
			@requests_fav.push(@request)
		end

		# カテゴリー別
		@requests_shipment = Request.where(category: "0").reverse_order
		@requests_event = Request.where(category: "1").reverse_order
		@requests_other = Request.where(category: "2").reverse_order

		# 月別
		@requests_spring = []
		@requests_summer = []
		@requests_autumn = []
		@requests_winter = []

		@requests.each do |r|
			if r.start_season.month == 3 || r.start_season.month == 4 || r.start_season.month == 5
				@requests_spring.push(r)
			elsif r.start_season.month == 6 || r.start_season.month == 7 || r.start_season.month == 8
	 			@requests_summer.push(r)
	 		elsif r.start_season.month == 9 || r.start_season.month == 10 || r.start_season.month == 11
	 			@requests_autumn.push(r)
	 		else
	 			@requests_winter.push(r)
			end
		end
	end

	def destroy
		request = Request.find(params[:id])
		if request.destroy
			redirect_to current_c_user, notice:"リクエストを削除しました！"
		end
	end

	def search
		@requests = Request.all.reverse_order.search(params[:search])
	end

	def login_user
		if f_user_signed_in? || c_user_signed_in?
		else
		 redirect_to :root
		end
	end

	def correct_user
		@user = Request.find(params[:id]).c_user
		redirect_to :root unless @user == current_c_user
	end

	private
	def request_params
		params.require(:request).permit(:title, :body, :location, :category, :status, :start_season, :finish_season, )
	end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_request_post.html.erb
<!-- ===== エラーメッセージ ===== -->
<% if @request.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
		<ul>
			<%= @request.errors.count %>件のエラーが発生しました。
			<% @request.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<!-- ===== 入力フォーム ===== -->
<div class="field ">
	<%= f.label :title ,"◇ タイトル" %>
	<%= f.text_field :title, class: "form-control" %>
</div>

<div class="field ">
	<%= f.label :start_season, "◇ 希望時期" %><br />
	<%= f.date_select :start_season, discard_day: true, class: "form-control" %>&emsp;〜&emsp;
	<%= f.date_select :finish_season, discard_day: true, class: "form-control" %>
</div>

<div class="field ">
	<%= f.label :location, "◇ 出荷先/開催地" %><br />
	<%= render 'layouts/location_select',f:f %>
</div>

<div class="field ">
	<%= f.label :category, "◇ カテゴリー" %><br />
	<%= f.select :category, [["農作物出荷","農作物出荷": 0],["体験/イベント", "体験/イベント": 1],["その他","その他": 2]], class: "form-control" %><br />
</div>

<div class="field ">
	<%= f.label :body, "◇ 希望内容/相談内容" %>
	<%= f.text_area :body, rows:"5", class: "form-control" %>
</div>

app/views/requests/_requests_index.html.erb
<!-- ===== カード ===== -->
<div class="col-md-4 col-sm-6 col-xs-12">
	<div class="requestCard ribbon_box">
		<!-- リボン(赤) -->
		<% if request.category == "農作物出荷" %>
			<span class="requestCard-ribbon ribbon0"><%= request.category%></span>
		<!-- リボン(水色) -->
		<% elsif request.category == "体験/イベント" %>
			<span class="requestCard-ribbon ribbon2"><%= request.category%></span>
		<!-- リボン(緑) -->
		<% else %>
			<span class="requestCard-ribbon ribbon3"><%= request.category%></span>
		<% end %>

		<!-- リクエスト概要 -->
		<div class="request-content">
			<h4>
				<%= link_to request_path(request) do%>
				<%= truncate(request.title, :omission => "...",:length => 35) %>
				<% end %>
			</h4>
			<p>
				<span class="item"><i class="fas fa-map-marker-alt"></i>&ensp;出荷先/開催地</span>&emsp;
				<b><%= request.location %></b><br>
				<span class="item"><i class="fas fa-calendar-alt"></i>&ensp;希望時期</span>&emsp;&emsp;&emsp;&emsp;
				<b><%= request.start_season.strftime('%Y年%m月') %>~<%= request.finish_season.strftime('%Y年%m月') %></b>
			</p>
		</div>
		<div class="requestCard-user">
			<i class="fas fa-home"></i>&ensp;<%= link_to request.c_user.company, request.c_user %>
		</div>

		<!-- bookmarkマーク -->
		<%= render 'favorite_stars/bookmarks',request:request %>
	</div>
</div>

app/views/requests/_search_form.html.erb
<div class="search">
	<%= form_tag(search_requests_path, :method => 'get' ) do %>
	<%= text_field_tag :search %>
	<%= submit_tag 'Search', :body => nil ,:location => nil%>
	<% end %>
</div>

app/views/requests/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 form-group">
			<h3><b>コラボリクエスト・編集</b></h3>
			<%= form_for(@request) do |f| %>
				<%= render 'requests/request_post',f:f %>
				<p class="actions">
					<%= f.submit "更新する" ,class: "btn btn-block btn-default btn-xs"%>
					<%= link_to '戻る', :back ,class: "btn btn-block btn-default btn-xs"%>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/requests/index.html.erb
<!-- ===== 画像 ===== -->
<div class="req-main-visual">
	<div class="req-main-visual-content">
		<p class="req-main-visual-text">
			様々な企業からの<br>
			コラボリクエストを掲載<br>
		</p>
	</div>
</div>

<div class="container">

	<div class="row">
		<h3 class=" index-headline"><b>企業からのコラボリクエスト</b></h3>

		<!-- === 検索フォーム === -->
		<%= render 'requests/search_form' %>

		<!-- === カテゴリ別タブメニュー === -->
		<%= render 'proposals/tab_menu' %>
	</div>

	<div id="tab-contents" class="row">
		<!-- -- All -- -->
		<div id="tab-all" class="tab">
			<% @requests.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 春/3月~5月 -- -->
		<div id="tab-spring" class="tab">
			<% @requests_spring.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 夏/6月~8月 -- -->
		<div id="tab-summer" class="tab">
			<% @requests_summer.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 秋/9月~11月 -- -->
		<div id="tab-autumn" class="tab">
			<% @requests_autumn.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 冬/12月~1月 -- -->
		<div id="tab-winter" class="tab">
			<% @requests_winter.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 農作物出荷 -- -->
		<div id="tab-shipment" class="tab">
			<% @requests_shipment.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 体験イベント -- -->
		<div id="tab-event" class="tab">
			<% @requests_event.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- その他 -- -->
		<div id="tab-other" class="tab">
			<% @requests_other.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>

		<!-- -- 登録済 -- -->
		<div id="tab-fav" class="tab">
			<% @requests_fav.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
			<% end %>
		</div>
	</div>
</div>

<!-- ===== topへ戻るボタン(ビューーンて動くやつ) ===== -->
<span id="back">
	<a href="#">
		<%= image_tag('arrow.png') %>
	</a>
</span>

app/views/requests/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 form-group">
			<h3><b>コラボリクエスト・新規投稿</b></h3>
			<%= form_for(@request) do |f| %>
				<%= render 'requests/request_post',f:f %>
				<p class="actions">
					<%= f.submit "投稿する" ,class: "btn btn-block btn-default btn-xs"%>
					<%= link_to '戻る', :back ,class: "btn btn-block btn-default btn-xs"%>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/requests/search.html.erb
<div class="container">

	<div class="row">
		<h3><b>コラボリクエスト [<%= "#{params[:search]}" %>] 検索結果</b></h3>
		<!-- === 検索フォーム === -->
		<%= render 'requests/search_form' %>
	</div>

	<div class="row">
		<!-- === 検索結果一覧 === -->
		<% @requests.each do |request| %>
			<%= render 'requests/requests_index',request:request %>
		<% end %>
	</div>
</div>

app/views/requests/show.html.erb
<div class="container">

	<!-- ===== サクセスメッセージ ===== -->
	<p id="notice"><%= notice %></p>

	<!-- ===== requestの内容 ===== -->
	<div class="row">
		<!-- === 投稿ユーザー表示 === -->
		<% if @c_user != current_c_user %>
			<h3 class="item-title color-base"><%= link_to @request.c_user.company, @request.c_user %>&ensp;からのプロポーザル</h3>
		<% end %>
		<!-- === 詳細内容 === -->
		<div class="request-show col-md-12">
			<!-- bookmark -->
			<%= render 'favorite_stars/bookmarks',request:@request %>
			<!-- テキスト -->
			<div class="col-md-10 col-md-offset-1">
				<h3><%= @request.title %></h3>
				<p class="request-category"><%= @request.category %></p>

				<p><i class="fas fa-calendar-alt"></i>&ensp;希望時期&emsp;<%= @request.start_season.strftime('%Y年%m月') %>&ensp;~&ensp;<%= @request.finish_season.strftime('%Y年%m月') %></p>
				<p><i class="fas fa-map-marker-alt"></i>&ensp;出荷先/開催地&emsp;<%= @request.location %></p>
				<p><i class="far fa-clipboard"></i>&ensp;リクエスト内容<br><%= simple_format(@request.body) %></p>
			</div>
			<!-- 削除・編集ボタン -->
			<% if @c_user == current_c_user %>
				<span class="pro-edit-link">
					&ensp;<%= link_to "",[:edit, @request], class: "glyphicon glyphicon-pencil" %>
					&ensp;|&ensp;<%= link_to "", @request, method: :delete, data: { confirm: '本当に削除しますか？'} ,class: "glyphicon glyphicon-trash" %>
				</span><br>
			<% end %>
		</div>
		<!-- === backボタン === -->
		<%= link_to '戻る', :back ,class: "col-md-1 col-md-offset-11 btn  btn-default btn-xs"%>
	</div>

	<!-- ===== favorite(bookmark) した人一覧 ===== -->
	<% if @c_user == current_c_user %>
		<div class="row favorited-users">
			<p class="item-title color-base col-md-offset-1">
				<span class="glyphicon glyphicon-bookmark"aria-hidden="true" style="color: orangered;"> </span>しているユーザー
			</p>
			<table class="table table-hover">
				<% @favorited_users.each do |favorited_user| %>
					<tr class="col-md-offset-1 col-md-10">
						<td class="col-md-1 col-md-offset-1">
							<%= attachment_image_tag(favorited_user, :image, :fill, 70, 70, fallback: "/images/farmer.png" ,class: "img-responsive img-thumbnail") %>
						</td>
						<td class="col-md-10">
							<b><%= link_to "#{favorited_user.farm} / #{favorited_user.name}", favorited_user %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	<% end %>

</div>