config/routes.rb
Rails.application.routes.draw do

  get '/' => 'root#top', as: 'root'

  devise_for :c_users, controllers: {
    sessions:      'c_users/sessions',
    passwords:     'c_users/passwords',
    registrations: 'c_users/registrations'
  }
  devise_for :f_users, controllers: {
    sessions:      'f_users/sessions',
    passwords:     'f_users/passwords',
    registrations: 'f_users/registrations'
  }
  resources :requests do
    get "search" , on: :collection
    resource :favorite_stars, only: [:create, :destroy,:show]
  end

  resources :proposals do
    get "search" , on: :collection
    resource :favorite_hearts, only: [:create, :destroy,:show]
  end

  resources :chatrooms, only: [ :show, :index] do
    resources :messages, only: [:create]
  end

  resources :crops_calendars,except: [:show]
  resources :blogs
  resources :f_users, except: [:new, :create,:index]
  resources :c_users, except: [:new, :create,:index]

end

app/models/proposal.rb
class Proposal < ApplicationRecord

	belongs_to :f_user
	has_many :favorite_hearts, dependent: :destroy
	has_many :c_users, through: :favorite_hearts

	attachment :p_image

	enum category: { "農作物出荷": 0, "体験/イベント": 1, "その他": 2 }

	validates :title         ,presence: true
	validates :body          ,presence: true
	validates :location      ,presence: true
	validates :start_season  ,presence: true
	validates :finish_season ,presence: true

	def favorited_by?(c_user)
		favorite_hearts.where(c_user_id: c_user.id).exists?
	end

	# 検索機能
	def self.search(search) #ここでのself.はProposal.を意味する
		if search
			where(['body LIKE ? OR location LIKE ?', "%#{search}%", "%#{search}%"]) #検索との部分一致を表示。#Proposal.は省略
		else
			all #全て表示。#Proposal.は省略
		end
	end

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

	before_action :login_user
	before_action :correct_user ,only:[:edit,:update,:destroy]

	def new
		@proposal = Proposal.new
	end

	def create
		@proposal = Proposal.new(proposal_params)
		@proposal.f_user_id = current_f_user.id
		if @proposal.save
			redirect_to @proposal, notice:'プロポーザルを追加しました！'
		else
			render :new
		end
	end

	def edit
		@proposal = Proposal.find(params[:id])
	end

	def update
		@proposal = Proposal.find(params[:id])
		if @proposal.update(proposal_params)
			redirect_to @proposal, notice:'プロポーザル内容を変更しました！'
		else
			render :edit
		end
	end

	def show
		@proposal = Proposal.find(params[:id])
		@f_user = @proposal.f_user

		# favorite_hearts(bookmark)した人一覧を出したい
		@favorited_users = []
		@favorited = FavoriteHeart.where(proposal_id: @proposal).reverse_order
		@favorited.each do |f|
			@favorited_user = CUser.find_by(id: f.c_user_id)
			@favorited_users.push(@favorited_user)
		end
	end

	def index
		@proposals = Proposal.all.reverse_order

		#favorite_hearts(bookmark)に登録したプロポーザルを取り出したい
		@favorites = FavoriteHeart.where("c_user_id = ?", current_c_user).reverse_order
		@proposals_fav = []
		@favorites.each do |f|
			@proposal = Proposal.find_by(id: f.proposal_id)
			@proposals_fav.push(@proposal)
		end

		# カテゴリー別
		@proposals_shipment = Proposal.where(category: "0").reverse_order
		@proposals_event = Proposal.where(category: "1").reverse_order
		@proposals_other = Proposal.where(category: "2").reverse_order

		# 月別
		@proposals_spring = []
		@proposals_summer = []
		@proposals_autumn = []
		@proposals_winter = []

		@proposals.each do |p|
			if p.start_season.month == 3 || p.start_season.month == 4 || p.start_season.month == 5
				@proposals_spring.push(p)
			elsif p.start_season.month == 6 || p.start_season.month == 7 || p.start_season.month == 8
	 			@proposals_summer.push(p)
	 		elsif p.start_season.month == 9 || p.start_season.month == 10 || p.start_season.month == 11
	 			@proposals_autumn.push(p)
	 		else
	 			@proposals_winter.push(p)
			end
		end
	end

	def destroy
		proposal = Proposal.find(params[:id])
		if proposal.destroy
			redirect_to current_f_user, notice:"プロポーザルを削除しました！"
		end
	end

	def search
		@proposals = Proposal.all.reverse_order.search(params[:search])
	end

	def login_user
		if f_user_signed_in? || c_user_signed_in?
		else
			redirect_to :root
		end
	end

	def correct_user
		@user = Proposal.find(params[:id]).f_user
		redirect_to :root unless @user == current_f_user
	end

	private
	def proposal_params
		params.require(:proposal).permit(:title, :body, :p_image, :location, :category, :status, :start_season, :finish_season, )
	end

end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_proposal_post.html.erb
<!-- ===== エラーメッセージ ===== -->
<% if @proposal.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
		<ul>
			<%= @proposal.errors.count %>件のエラーが発生しました。
			<% @proposal.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<!-- ===== 入力フォーム ===== -->
<div class="field ">
	<%= f.label :title ,"◇ タイトル" %>
	<%= f.text_field :title, class: "form-control" %>
</div>

<div class="field ">
	<%= f.label :start_season, "◇ 出荷時期/開催時期" %><br />
	<%= f.date_select :start_season, discard_day: true, class: "form-control" %>&emsp;〜&emsp;
	<%= f.date_select :finish_season, discard_day: true, class: "form-control" %>
</div>

<div class="field ">
	<%= f.label :location, "◇ 出荷元/開催地" %><br />
	<%= render 'layouts/location_select',f:f %>
</div>

<div class="field ">
	<%= f.label :category, "◇ カテゴリー" %><br />
	<%= f.select :category,[["農作物出荷","農作物出荷": 0],["体験/イベント", "体験/イベント": 1],["その他","その他": 2]],  class: "form-control" %><br />
</div>

<div class="field ">
	<%= f.label :body, "◇ できること/提案内容" %>
	<%= f.text_area :body, rows:"5", class: "form-control" %>
</div>

<div class="field ">
	<%= f.label :p_image,"◇ 写真" %>
	<%= f.attachment_field :p_image %>
</div>

app/views/proposals/_proposals_index.html.erb
<!-- ===== カード ===== -->
<div class="col-md-4 col-sm-6 col-xs-12">
	<div class="proposalCard">

		<!-- === 画像 & リボン === -->
		<div class="proposalCard-image ribbon_box">
			<!-- リボン(赤) -->
			<% if proposal.category == "農作物出荷" %>
				<span class="proposalCard-ribbon ribbon0"><%= proposal.category%></span>
				<%= link_to attachment_image_tag(proposal, :p_image, fallback:"/images/Vegetables.png",class: "img-responsive"), proposal  %>
			<!-- リボン(水色) -->
			<% elsif proposal.category == "体験/イベント" %>
				<span class="proposalCard-ribbon ribbon2"><%= proposal.category%></span>
				<%= link_to attachment_image_tag(proposal, :p_image, fallback:"/images/Experience.png",class: "img-responsive"), proposal %>
			<!-- リボン(緑) -->
			<% else %>
				<span class="proposalCard-ribbon ribbon3"><%= proposal.category%></span>
				<%= link_to attachment_image_tag(proposal, :p_image, fallback:"/images/Vegetables.png",class: "img-responsive"), proposal  %>
			<% end %>
		</div>

		<!-- === テキスト === -->
		<div class="proposalCard-thum">
			<div class="content">
				<h4>
					<%= link_to proposal_path(proposal) do%>
					<%= truncate(proposal.title, :omission => "...") %>
					<% end %>
				</h4>
				<p>
					<span class="item"><i class="fas fa-calendar-alt"></i>&ensp;出荷時期/開催時期</span>&emsp;
					<b><%= proposal.start_season.strftime('%Y年%m月') %>~<%= proposal.finish_season.strftime('%Y年%m月') %></b><br>
					<span class="item"><i class="fas fa-map-marker-alt"></i>&ensp;出荷元/開催地</span>&emsp;&emsp;&emsp;&ensp;
					<b><%= proposal.location %></b>
				</p>
			</div>
			<div class="proposalCard-user">
				<i class="fas fa-home"></i>&ensp;<%= link_to proposal.f_user.farm, proposal.f_user %>
			</div>
			<!-- bookmarkマーク -->
			<%= render 'favorite_hearts/bookmarks',proposal:proposal %>
		</div>

	</div>
</div>

app/views/proposals/_search_form.html.erb
<div class="search">
	<%= form_tag(search_proposals_path, :method => 'get' ) do %>
		<%= text_field_tag :search %>
		<%= submit_tag 'Search', :body => nil ,:location => nil%>
	<% end %>
</div>

app/views/proposals/_tab_menu.html.erb
<div id="tab-menu" class="col-md-12 clearfix" >
	<a href="#tab-spring" class="tab-btn btn col-md-1">春<br>3月~5月</a>
	<a href="#tab-summer" class="tab-btn btn col-md-1">夏<br>6月~8月</a>
	<a href="#tab-autumn" class="tab-btn btn col-md-1">秋<br>9月~11月</a>
	<a href="#tab-winter" class="tab-btn btn col-md-1">冬<br>12月~1月</a>

	<a href="#tab-shipment" class="tab-btn btn col-md-1 col-md-offset-1">農作物<br>出荷</a>
	<a href="#tab-event" class="tab-btn btn col-md-1">体験/<br>イベント</a>
	<a href="#tab-other" class="tab-btn btn col-md-1">その他<br>&emsp;</a>

	<a href="#tab-fav" class="tab-btn btn col-md-1 col-md-offset-1">登録済<br><span class="glyphicon glyphicon-bookmark"></span></a>

	<a href="#tab-all" class="tab-btn btn col-md-1 col-md-offset-1 active">ALL<br>&emsp;</a>

</div>

app/views/proposals/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 form-group">
			<h3><b>プロポーザル・編集</b></h3>
			<%= form_for(@proposal) do |f| %>
				<%= render 'proposals/proposal_post',f:f %>
				<p class="actions">
					<%= f.submit "更新する" ,class: "btn btn-block btn-default btn-xs"%>
					<%= link_to '戻る', :back ,class: "btn btn-block btn-default btn-xs"%>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/proposals/index.html.erb
<!-- ===== 画像 ===== -->
<div class="pro-main-visual">
	<div class="pro-main-visual-content">
		<p class="pro-main-visual-text">
			生産者からの<br>
			プロポーザルを掲載<br>
		</p>
	</div>
</div>

<div class="container ">
	<div class="row">
		<h3 class=" index-headline"><b>生産者からのプロポーザル</b></h3>

		<!-- === 検索フォーム === -->
		<%= render 'proposals/search_form' %>

		<!-- === カテゴリ別タブメニュー === -->
		<%= render 'proposals/tab_menu' %>
	</div>

	<!-- ===== カテゴリ別index ===== -->
	<div id="tab-contents" class="row">
		<!-- -- All -- -->
		<div id="tab-all" class="tab ">
			<% @proposals.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 春/3月~5月 -- -->
		<div id="tab-spring" class="tab">
			<% @proposals_spring.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 夏/6月~8月 -- -->
		<div id="tab-summer" class="tab">
			<% @proposals_summer.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 秋/9月~11月 -- -->
		<div id="tab-autumn" class="tab">
			<% @proposals_autumn.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 冬/12月~1月 -- -->
		<div id="tab-winter" class="tab">
			<% @proposals_winter.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 農作物出荷 -- -->
		<div id="tab-shipment" class="tab">
			<% @proposals_shipment.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 体験イベント -- -->
		<div id="tab-event" class="tab">
			<% @proposals_event.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- その他 -- -->
		<div id="tab-other" class="tab">
			<% @proposals_other.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>

		<!-- -- 登録済 -- -->
		<div id="tab-fav" class="tab">
			<% @proposals_fav.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
			<% end %>
		</div>
	</div>
</div>

<!-- ===== topへ戻るボタン(ビューーンて動くやつ) ===== -->
<span id="back">
	<a href="#">
		<%= image_tag('arrow.png') %>
	</a>
</span>

app/views/proposals/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 form-group">
			<h3><b>プロポーザル・新規投稿</b></h3>
			<%= form_for(@proposal) do |f| %>
				<%= render 'proposals/proposal_post',f:f %>
				<p class="actions">
					<%= f.submit "投稿する" ,class: "btn btn-block btn-default btn-xs"%>
					<%= link_to '戻る', :back ,class: "btn btn-block btn-default btn-xs"%>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/proposals/search.html.erb
<div class="container">
	<div class="row">
		<h3><b>プロポーザル [<%= "#{params[:search]}" %>] 検索結果</b></h3>
		<!-- === 検索フォーム === -->
		<%= render 'proposals/search_form' %>
	</div>

	<div class="row">
		<!-- === 検索結果一覧 === -->
		<% @proposals.each do |proposal| %>
			<%= render 'proposals/proposals_index',proposal:proposal %>
		<% end %>
	</div>
</div>

app/views/proposals/show.html.erb
<div class="container">

	<!-- ===== サクセスメッセージ ===== -->
	<p id="notice"><%= notice %></p>

	<!-- ===== proposalの内容 ===== -->
	<div class=" row">
		<!-- === 投稿ユーザー表示 === -->
		<% if @f_user != current_f_user %>
			<h3 class="item-title color-base"><%= link_to @proposal.f_user.farm, @proposal.f_user %>&ensp;からのプロポーザル</h3>
		<% end %>
		<!-- === 詳細内容 === -->
		<div class="col-md-12 proposal_show">
			<!-- bookmark -->
			<%= render 'favorite_hearts/bookmarks',proposal:@proposal %>
			<!-- テキスト -->
			<div class="col-md-7 col-md-offset-1">
			    <h3><%= @proposal.title %></h3>
				<p class="proposal-category"><%= @proposal.category %></p>
				<p><i class="fas fa-calendar-alt"></i>&ensp;出荷時期/開催時期&emsp;<%= @proposal.start_season.strftime('%Y年%m月') %>&ensp;~&ensp;<%= @proposal.finish_season.strftime('%Y年%m月') %></p>
				<p><i class="fas fa-map-marker-alt"></i>&ensp;出荷元/開催地&emsp;<%= @proposal.location %></p>
				<p><i class="far fa-clipboard"></i>&ensp;提案内容<br><%= simple_format(@proposal.body) %></p>
			</div>
			<!-- 画像 -->
			<div class="col-md-3 proposal-image">
				<% if @proposal.category == "体験/イベント" %>
				<%= attachment_image_tag @proposal, :p_image, fallback:"/images/Experience.png",class: "img-responsive img-thumbnail" %>
				<% else %>
				<%= attachment_image_tag @proposal, :p_image, fallback:"/images/Vegetables.png",class: "img-responsive img-thumbnail" %>
				<% end %>
			</div>
			<!-- 削除・編集ボタン -->
			<% if @f_user == current_f_user %>
				<span class="pro-edit-link">
					&ensp;<%= link_to "",[:edit, @proposal], class: "glyphicon glyphicon-pencil" %>
					&ensp;|&ensp;<%= link_to "", @proposal, method: :delete, data: { confirm: '本当に削除しますか？'} ,class: "glyphicon glyphicon-trash" %>
				</span>
			<% end %>
		</div>
		<!-- === backボタン === -->
		<%= link_to '戻る', :back ,class: "col-md-1 col-md-offset-11 btn  btn-default btn-xs"%>
	</div>


	<!-- ===== favorite(bookmark) した人一覧 ===== -->
	<% if @f_user == current_f_user %>
		<div class="row favorited-users">
			<p class="item-title color-base col-md-offset-1">
				<span class="glyphicon glyphicon-bookmark"aria-hidden="true" style="color: orangered;"> </span>しているユーザー
			</p>
			<table class="table table-hover">
				<% @favorited_users.each do |favorited_user| %>
					<tr class="col-md-offset-1 col-md-10">
						<td class="col-md-1 col-md-offset-1">
							<%= attachment_image_tag(favorited_user, :image, :fill, 70, 70, fallback: "/images/company.png" ,class: "img-responsive img-thumbnail") %>
						</td>
						<td class="col-md-10">
							<b><%= link_to "#{favorited_user.company} / #{favorited_user.name}", favorited_user %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	<% end %>

</div>